services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.3
    environment:
      - CERT_TOOL_VERSION=4.14
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml
