services:
  wazuh-overlay-gateway:
    image: alpine:3.20
    container_name: wazuh-overlay-gateway
    depends_on:
      - netbird-peer-wazuh
      - wazuh.manager
    network_mode: "service:netbird-peer-wazuh"
    command: >
      sh -lc '
        apk add --no-cache socat >/dev/null &&
        echo "Forwarding overlay -> wazuh.manager (1514/tcp, 1515/tcp, 55000/tcp, 514/udp)" &&
        socat TCP-LISTEN:1514,fork,reuseaddr TCP:wazuh.manager:1514 &
        socat TCP-LISTEN:1515,fork,reuseaddr TCP:wazuh.manager:1515 &
        socat TCP-LISTEN:55000,fork,reuseaddr TCP:wazuh.manager:55000 &
        socat UDP-RECVFROM:514,fork,reuseaddr UDP-SENDTO:wazuh.manager:514 &
        wait
      '

  ubuntu-agent-wazuh-net:
    build:
      context: ./wazuh-agent-ubuntu
    container_name: ubuntu-agent-wazuh-net
    hostname: ubuntu-agent-wazuh-net
    networks:
      - wazuh_net
    environment:
      - WAZUH_MANAGER=wazuh.manager
      - WAZUH_AGENT_NAME=ubuntu-agent-wazuh-net
    depends_on:
      - wazuh.manager

  ubuntu-agent-nb1:
    build:
      context: ./wazuh-agent-ubuntu
    container_name: ubuntu-agent-nb1
    hostname: ubuntu-agent-nb1
    network_mode: "service:netbird-peer-1"
    environment:
      - WAZUH_MANAGER=${WAZUH_OVERLAY_ADDR}
      - WAZUH_AGENT_NAME=ubuntu-agent-nb1
    depends_on:
      - wazuh-overlay-gateway
      - netbird-peer-1

  ubuntu-agent-nb2:
    build:
      context: ./wazuh-agent-ubuntu
    container_name: ubuntu-agent-nb2
    hostname: ubuntu-agent-nb2
    network_mode: "service:netbird-peer-2"
    environment:
      - WAZUH_MANAGER=${WAZUH_OVERLAY_ADDR}
      - WAZUH_AGENT_NAME=ubuntu-agent-nb2
    depends_on:
      - wazuh-overlay-gateway
      - netbird-peer-2

  ubuntu-agent-nb3:
    build:
      context: ./wazuh-agent-ubuntu
    container_name: ubuntu-agent-nb3
    hostname: ubuntu-agent-nb3
    network_mode: "service:netbird-peer-3"
    environment:
      - WAZUH_MANAGER=${WAZUH_OVERLAY_ADDR}
      - WAZUH_AGENT_NAME=ubuntu-agent-nb3
    depends_on:
      - wazuh-overlay-gateway
      - netbird-peer-3
